matrix:
  include:
    - language: python
      python:
        - "3.6"
      before_script:
        - pip install docker-compose
      before_install:
        - cd backend/trun
      script:
        - python manage.py test
      services:
        docker

    - language: node_js
      node_js:
        - "13.12.0"
      before_install:
        - cd frontend 
      install:
        npm install
      script:
        - npm test
      services:
        docker
