# Generated by Django 3.0.5 on 2020-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
